import { PaymentFor, PaymentGateway, PaymentStatus } from "../enums";

export interface Payment {
  _id: string,
  transactionId: string,
  paymentStatus: PaymentStatus,
  paymentMethod: string,
  paymentGateway: PaymentGateway,
  paymentFor: PaymentFor,
  initialAmount: number,
  discountAmount: number,
  totalAmount: number,
  userId?: string | null,
  providerId?: string | null,
  refundId?: string | null,
  refundAmount?: number | null,
  refundStatus?: string | null,
  refundAt?: Date | null,
  refundReason?: string | null,
  chargeId?: string | null,
  receiptUrl?: string | null,
  receiptNumber?: string | null,
  receiptEmail?: string | null,
  customerEmail?: string | null,
  description?: string | null,
  createdAt: Date,
  updatedAt: Date,
}